[package]
name = "part_5_ray_trace_multithread_scanlines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = { workspace = true }